//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba4_ptpm
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string name { get; set; }
        public int phone { get; set; }
        public string Role { get; set; }
        public User()
        { }
        public User(string Login, string Password, string name, int phone, string role)
        {
            this.Login = Login;
            this.Password = Password;
            this.name = name;
            this.phone = phone;
            this.Role = role;
        }
    }
}
